import os
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch


def generate_pdf_report(patient_name, patient_age, scan_id, diagnosis, confidence):
    """
    Generates professional hospital-style PDF report
    """

    # Ensure values are not empty
    patient_name = patient_name if patient_name else "N/A"
    patient_age = patient_age if patient_age else "N/A"
    scan_id = scan_id if scan_id else "N/A"

    file_name = f"{patient_name}_Brain_Tumor_Report.pdf"
    pdf_path = os.path.join(os.getcwd(), file_name)

    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    elements = []

    styles = getSampleStyleSheet()
    normal = styles["Normal"]
    heading = styles["Heading1"]
    subheading = styles["Heading2"]

    # Title
    elements.append(Paragraph("AI Radiology Diagnostic Report", heading))
    elements.append(Spacer(1, 0.4 * inch))

    # Patient Info
    elements.append(Paragraph("<b>Patient Information</b>", subheading))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph(f"<b>Name:</b> {patient_name}", normal))
    elements.append(Paragraph(f"<b>Age:</b> {patient_age}", normal))
    elements.append(Paragraph(f"<b>Scan ID:</b> {scan_id}", normal))
    elements.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal))
    elements.append(Spacer(1, 0.4 * inch))

    # Diagnosis Section
    elements.append(Paragraph("<b>AI Diagnosis Result</b>", subheading))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph(f"<b>Predicted Class:</b> {diagnosis}", normal))
    elements.append(Paragraph(f"<b>Confidence Score:</b> {confidence * 100:.2f}%", normal))
    elements.append(Spacer(1, 0.4 * inch))

    # Disclaimer
    elements.append(Paragraph(
        "Disclaimer: This report is generated by an AI deep learning model. "
        "It is intended for research and assistance purposes only. "
        "Please consult a certified medical professional for final diagnosis.",
        normal
    ))

    doc.build(elements)

    return pdf_path
